In [2]:
import numpy as np

In [5]:

def hello_world(name: str):
    print(f"Hello, {name}")

In [8]:
def factorial(num: int) -> int:
    if(num == 0 or num == 1):
        return 1
    return num * factorial(num - 1)

In [10]:
def suma_gauss(num: int) -> int:
    if(num == 1):
        return 1
    return num + suma_gauss(num - 1)

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix2 = np.array([[9,8,7], [6,5,4], [3,2,1]])
print("========================================")
print(matrix)
print("========================================")

print(matrix2)
print("========================================")

print(matrix + matrix2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [11]:
hello_world("world!")
fact = factorial(5)
print(fact)
print(suma_gauss(5))

Hello, world!
120
15
