In [6]:
import numpy as np

In [2]:

def hello_world(name: str):
    print(f"Hello, {name}")

In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
hello_world("Gerardo")

Hello, Gerardo
